### ISSUE TITLE
FTBFS somewhere in python setup.py install ... installing egg_info?

### ISSUE THREAD

**Issue by mcepl** [dephell/dephell_markers#6] opened 2019-12-02 09:58 UTC
I am not sure what’s wrong, but when building the package (version 1.0.2 from the released tarball) I get this:

```
[   31s] + /usr/bin/python3 setup.py install -O1 --skip-build --force --root /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64 --prefix /usr
[   31s] running install
[   31s] running install_lib
[   31s] creating /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr
[   31s] creating /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib
[   31s] creating /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7
[   31s] creating /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages
[   31s] creating /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers
[   31s] copying build/lib/dephell_markers/_cached_property.py -> /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers
[   31s] copying build/lib/dephell_markers/_constants.py -> /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers
[   31s] copying build/lib/dephell_markers/__init__.py -> /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers
[   31s] copying build/lib/dephell_markers/_markers.py -> /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers
[   31s] creating /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers/_marker
[   31s] copying build/lib/dephell_markers/_marker/_version.py -> /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers/_marker
[   31s] copying build/lib/dephell_markers/_marker/_base.py -> /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers/_marker
[   31s] copying build/lib/dephell_markers/_marker/__init__.py -> /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers/_marker
[   31s] copying build/lib/dephell_markers/_marker/_string.py -> /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers/_marker
[   31s] creating /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers/_operation
[   31s] copying build/lib/dephell_markers/_operation/_or.py -> /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers/_operation
[   31s] copying build/lib/dephell_markers/_operation/_base.py -> /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers/_operation
[   31s] copying build/lib/dephell_markers/_operation/__init__.py -> /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers/_operation
[   31s] copying build/lib/dephell_markers/_operation/_and.py -> /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers/_operation
[   31s] byte-compiling /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers/__init__.py to __init__.cpython-37.pyc
[   31s] byte-compiling /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers/_cached_property.py to _cached_property.cpython-37.pyc
[   31s] byte-compiling /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers/_constants.py to _constants.cpython-37.pyc
[   31s] byte-compiling /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers/_marker/__init__.py to __init__.cpython-37.pyc
[   31s] byte-compiling /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers/_marker/_base.py to _base.cpython-37.pyc
[   31s] byte-compiling /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers/_marker/_string.py to _string.cpython-37.pyc
[   31s] byte-compiling /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers/_marker/_version.py to _version.cpython-37.pyc
[   31s] byte-compiling /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers/_markers.py to _markers.cpython-37.pyc
[   31s] byte-compiling /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers/_operation/__init__.py to __init__.cpython-37.pyc
[   31s] byte-compiling /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers/_operation/_and.py to _and.cpython-37.pyc
[   31s] byte-compiling /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers/_operation/_base.py to _base.cpython-37.pyc
[   31s] byte-compiling /home/abuild/rpmbuild/BUILDROOT/python-dephell-markers-1.0.2-0.x86_64/usr/lib/python3.7/site-packages/dephell_markers/_operation/_or.py to _or.cpython-37.pyc
[   31s] writing byte-compilation script '/tmp/tmpc71pyy4r.py'
[   31s] /usr/bin/python3 /tmp/tmpc71pyy4r.py
[   31s] removing /tmp/tmpc71pyy4r.py
[   31s] running install_egg_info
[   31s] error: error in 'egg_base' option: '' does not exist or is not a directory
[   31s] error: Bad exit status from /var/tmp/rpm-tmp.mNcdbA (%install)
[   31s] 
[   31s] 
[   31s] RPM build errors:
[   31s]     Bad exit status from /var/tmp/rpm-tmp.mNcdbA (%install)
[   31s] 
[   31s] stitny failed "build python-dephell-markers.spec" at Mon Dec  2 09:52:22 UTC 2019.
[   31s] 
```

[Complete build log with all details](https://github.com/dephell/dephell_markers/files/3910571/_log.txt)

**Comment by mcepl** [comment] 2019-12-02 10:19
[pdb session investigating the issue](https://gist.github.com/mcepl/8641ad5dfda401fcc0baea4da6f3596e)

**Comment by jayvdb** [comment] 2019-12-09 09:07
The problem is the `package_dir={'': ''},` in the generated `setup.py`.  When I remove it, the install works.

openSUSE change request https://build.opensuse.org/request/show/755150

https://github.com/dephell/dephell/commit/d9b3c96472ef might have fixed it @orsinium @melko  , so maybe regen the setup.py ?

**Comment by jayvdb** [comment] 2019-12-09 12:16
I've verified the problem still exists in any generated setup.py in the latest releases of dephell.

**Comment by eli-schwartz** [comment] 2019-12-18 06:08
That's actually fixed by https://github.com/dephell/dephell_discover/pull/11 and https://github.com/dephell/dephell_discover/commit/20ca243922e8d268ac3cb2227f7953175118df64, so you should be looking at the latest release of dephell_discover instead.

**Comment by orsinium** [comment] 2019-12-18 10:30
Ah, right. Some packages were built by a broken dephell dev version. I've rebuilt and upload it. Please, use 1.0.3.

**Closed by orsinium** 2019-12-18 10:30 UTC
